# Netlify configuration for Vite static site
# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"

# Optional: redirect all routes to index.html for single-page apps
[[redirects]]
  from = "/**"
  to = "/index.html"
  status = 200
